<a href="https://colab.research.google.com/github/tubagusmfyoga/DataEngineer-FSBangalore/blob/main/sesi06_DataIntegrationWithAPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Web Scraping**
Scraping data (sering juga ditulis web scraping) adalah teknik mengambil data dari website atau sumber online secara otomatis menggunakan program.

# Tugas Scraping Review Aplikasi Mobile Bank Syariah

# Install Library Googleplay Scraper

In [1]:
pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 3.2 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

# Gunakan fitur Search dari Library Googleplay Scraper untuk search data yang mau scraping dan tampilkan Hasilnya

In [2]:
#Melakukan Search Data dari "Bank Syariah"
from google_play_scraper import search

results=search(
    "bank syariah",
    lang="id",
    country="id",
    n_hits=50
)

#Menampilkan Hasil
display(results)

[{'appId': 'co.id.newmb.btnsyariah',
  'icon': 'https://play-lh.googleusercontent.com/zq2Dyn4YGB3pTYrWh19mrxIpB4581ExyTaseevXQjiehVbTY4dy46tsZu-rndzUJK9Lix4HsmmYD036vKuLV',
  'screenshots': ['https://play-lh.googleusercontent.com/Ww32aTO8a8aDmIzfEf6tKbMgAQZi-jpAE6lUTXaplKxyciRlYB6hyoMKfHhFat4TinReku4dFCc6DM38adZKXw',
   'https://play-lh.googleusercontent.com/gNxriGmoMsAp9MyxpMbf-ZhM2BAEX4-osEQITW7wogeAYzUd3sO830UYDK29A4V-Giwqjzlseota0QrF-mz6FY8',
   'https://play-lh.googleusercontent.com/BqoeuqL0lCknk_JhFjn71FhBAqFU8PxEETYIJuxdbB5tKHAGwI2XFsMi9n74XKOfG5w4sgTQ7pNMB5wtTuy6',
   'https://play-lh.googleusercontent.com/nbvoAtk3bitgqYcxPQZUB5pYabN1loGRnphOEQCV4aHEnXiR_AVUACwX31fSktaTO2VO7UgOv7qClq5wwbL-PA',
   'https://play-lh.googleusercontent.com/Ww32aTO8a8aDmIzfEf6tKbMgAQZi-jpAE6lUTXaplKxyciRlYB6hyoMKfHhFat4TinReku4dFCc6DM38adZKXw',
   'https://play-lh.googleusercontent.com/gNxriGmoMsAp9MyxpMbf-ZhM2BAEX4-osEQITW7wogeAYzUd3sO830UYDK29A4V-Giwqjzlseota0QrF-mz6FY8',
   'https://play-lh.googleusercontent.com/BqoeuqL0lCknk_JhFjn71FhBAqFU8PxEETYIJuxdbB5tKHAGwI2XFsMi9n74XKOfG5w4sgTQ7pNMB5wtTuy6',
   'https://play-lh.googleusercontent.com/nbvoAtk3bitgqYcxPQZUB5pYabN1loGRnphOEQCV4aHEnXiR_AVUACwX31fSktaTO2VO7UgOv7qClq5wwbL-PA',
   'https://play-lh.googleusercontent.com/Ww32aTO8a8aDmIzfEf6tKbMgAQZi-jpAE6lUTXaplKxyciRlYB6hyoMKfHhFat4TinReku4dFCc6DM38adZKXw',
   'https://play-lh.googleusercontent.com/gNxriGmoMsAp9MyxpMbf-ZhM2BAEX4-osEQITW7wogeAYzUd3sO830UYDK29A4V-Giwqjzlseota0QrF-mz6FY8',
   'https://play-lh.googleusercontent.com/BqoeuqL0lCknk_JhFjn71FhBAqFU8PxEETYIJuxdbB5tKHAGwI2XFsMi9n74XKOfG5w4sgTQ7pNMB5wtTuy6',
   'https://play-lh.googleusercontent.com/nbvoAtk3bitgqYcxPQZUB5pYabN1loGRnphOEQCV4aHEnXiR_AVUACwX31fSktaTO2VO7UgOv7qClq5wwbL-PA',
   'https://play-lh.googleusercontent.com/ruZJJT1Xv_rIVecFBF95_4fWXy6eXpOyFp2q7_dhAULmMtgPopwfYNDUVbFLbxfF8xyf4oIG5Z1Fskdp24SLpw'],
  'title': 'Bale Syariah By BSN',
  'score': 4.5799255,
  'genre': 'Keuangan',
  'price': 0,
  'free': True,
  'currency': 'IDR',
  'video': None,
  'videoImage': None,
  'description': 'Bale Syariah By BSN adalah layanan mobile banking terbaru yang dipersiapkan untuk nasabah, agar dapat melakukan transaksi finansial, sosial dan spiritual dimanapun dan kapanpun dengan aman dan nyaman.',
  'descriptionHTML': 'Bale Syariah By BSN adalah layanan mobile banking terbaru yang dipersiapkan untuk nasabah, agar dapat melakukan transaksi finansial, sosial dan spiritual dimanapun dan kapanpun dengan aman dan nyaman.',
  'developer': 'PT Bank Syariah Nasional',
  'installs': '100.000+'},
 {'appId': 'id.co.bcasyariah.bsya',
  'icon': 'https://play-lh.googleusercontent.com/-Q1Y55AjNEF9Lfi6to1x_AwCcdOfbErwu1TraDZYlUdbg3AE9Y2wFunhJKG4fYRcYBo',
  'screenshots': ['https://play-lh.googleusercontent.com/49vMaLwhz4OqI5aI8M4T37Qumk13adSxDveHlfdwp5TUlwFGE30zjig-1JV-I4Z_8QA',
   'https://play-lh.googleusercontent.com/xJXi7vuknT19GdLJlUxWKCur2vXQnK-uivZXXCBmLpiDbntnID15V_rZ7lJ-gKoLeLhn',
   'https://play-lh.googleusercontent.com/r7hUlGd9kzV-Naz84Mvmv5F7Xiklp5Rxa1GlHWx6WLtrpWFWu7wT5p56vsjwRYVLlg',
   'https://play-lh.googleusercontent.com/T6r4nNZH8fu8sttk_puri094-YfTOxdX2OfoH2dE0G5byMg5CS-2Qlfk45uc0JcnPRk',
   'https://play-lh.googleusercontent.com/_XK5pn6K3VDrEHYB7ZG4iTd2NomuRxB3tJXm8k3nMZ6wuj5wKTJr4TRaYtNII7BAyudS',
   'https://play-lh.googleusercontent.com/afbugcRguukzkCrBuR0UhFyetLekFKb3DbLSAp7oLDaNI6DOjKQeyYP1EGAIom-GSw',
   'https://play-lh.googleusercontent.com/01iNB8li0zgotwdycYRrJ1IzhAN6VdLxqVNmQw_oH8L0ODKjn_Z6WJBg4s4oD4fM_yZw',
   'https://play-lh.googleusercontent.com/0oWrNzk8XJEdaia4PYfAm6FPCrN6N5UMlsW__NTWoG34feQK-jiBw256B2jeXNnxhg',
   'https://play-lh.googleusercontent.com/TvV85OyfvGDiBGiv7yZ0Axg010ZhGt2PfWfT-P8wRKgjdxaESIrL-TtyO06d_6qQnw4',
   'https://play-lh.googleusercontent.com/SHn1GFgCVPj-bNYB13W7HVH6ArLl-ScpDHWadxou7mLi__nHk4ZWJyusubiDlNOuBDI',
   'https://play-lh.googleusercontent.com/gIIuUJOJK2UhF_m28OIYsIbM9UBOXuyBfREsiLHonWWp8kOyXl5cIkZwCAyZ_7gqVv8',
   'https://play-lh.googleusercontent.com/3E0St4nSysSDgpKXXjYh2Xc1ZIZqxeRLatSN9HlutCTuwt6aqbWtLJ3OLo-pWdj7oQ',
   'https://play-lh.googleusercontent.com/TcoxwF0Bg_MxuvlcaCWkuJvexLxxEUPKphg3o_c22wk2Ko-vzbzRYk-4jATl6xee4y0',
   'https://play-lh.googleusercontent.com/oH6qLPC5AdbR-oJFEY7-lRWM9Pa7Eoxd7nc23qZGfpG1nO73UcNU3PMeTuIPuRXa2Zg',
   'https://play-lh.googleusercontent.com/jvN3TzQ6AzcLGS0h2RX5r0bFDnHmgmPfqWqdgJvM5yNq5heAmjMZ9d3DBkOYkk8pMUe8',
   'https://play-lh.googleusercontent.com/bTfJxNQicfclBrLYx0ro49HGQtT9ZpbBJxhEnBTc5HdWGZpDiixy6sYReQJD_U8qzT8',
   'https://play-lh.googleusercontent.com/AvcszOek5Nk9JuPIWB90WnX6J1PsHnweauty4JUCkdlVVe6MlMcwrwmXT_h6XKohv5bi',
   'https://play-lh.googleusercontent.com/Xv8vl_toyLKaDZ10t8lGlqlGY5fWMgUykfvsiTC_4F5oIb6y8oDhmJ-w0EbPeX2XEVg',
   'https://play-lh.googleusercontent.com/AAeayGdki221bm34lABvRwn_O7GPzIojqmtMJQzgkNq4r6BCIUjpU1WYj3Ek73ZdwA',
   'https://play-lh.googleusercontent.com/NQ5Og597p2tYETs7YQtQKAp8ptKUgQvnmtKZRkKFUMB2MyDgUzpqJa51S9_HTdCAY0I',
   'https://play-lh.googleusercontent.com/AJPhYW5EEwlcr_CaRHRi4fHhg3wwtVoovQFPM2wddITl-PBz1gRN3E8xjCZFd1-hJow9',
   'https://play-lh.googleusercontent.com/2vXufQO3IXxOeM67fHmhfOkM0Zl0HD_BZJ8mm9oT-I3MN9J53wnFLBjKj4saeI32Ww',
   'https://play-lh.googleusercontent.com/zNhcygi2qtpAOAb84dp6U0AkRyDv_ijYk3Xm9F_byAtiLSHO1lIEyS9GzyBkppzUUwk',
   'https://play-lh.googleusercontent.com/nj3LrIHbLXyLMzJo1X9peXUAXiM44oR3Rh8s4wIzOZYbmOjvnN1zcIgmNEQ7ncJdpg',
   'https://play-lh.googleusercontent.com/L2sJjnOK7qgeebVIe86SftxIHxJsaZl9ViueQTYiy7wJaQl4YCBt3UGdNbao5tW-Vuo'],
  'title': 'BSya by BCA Syariah',
  'score': 3.2555556,
  'genre': 'Keuangan',
  'price': 0,
  'free': True,
  'currency': 'IDR',
  'video': None,
  'videoImage': None,
  'description': 'Kenapa harus pake BSya? Yuk simak keunggulan BSya berikut ini:\r\n \r\nFitur Lebih Lengkap\r\nKebutuhan transaksi kamu dapat terpenuhi dengan berbagai fitur, baik fitur transaksi finansial maupun transaksi non finansial.\r\n \r\nNyaman\r\nCukup satu aplikasi untuk mengakses semua rekening kamu, kapanpun dan dimanapun. \r\n \r\nAman\r\nTransaksi lebih aman dengan proteksi maksimal yang dilengkapi dengan sistem biometrik, kode akses dan mPIN.\r\n \r\nFitur BSya\r\n• Pembukaan rekening online\r\n• Transfer ke rekening BCA Syariah, Grup BCA, Virtual Account dan ke Bank Lain\r\n• Pembelian dan pembayaran\r\n• Mutasi rekening & histori transaksi\r\n• Informasi detail rekening deposito dan pembiayaan\r\n• Pembayaran QRIS\r\n• Top up e-Wallet\r\n• Tarik tunai tanpa kartu, baik melalui fitur Cardless maupun eBranch\r\n• Setoran biaya haji dan informasi RTJH\r\n• Informasi rekening (cek saldo, mutasi rekening dan histori transaksi)\r\n• Informasi jadwal sholat dan arah kiblat sesuai lokasi kamu\r\n• Layanan contact center melalui Halo BCA\r\n \r\nGak cuma itu.. Pembukaan rekening online di BSya juga dilengkapi dengan fitur autodebet Zakat. Ditambah lagi fitur-fitur yang memudahkan ibadah kamu seperti jadwal shalat dan arah kiblat. Jadi lebih berkah kan.. \r\n \r\nInfo penting yang kamu perlu tahu! Jadi tim FrenS BCA Syariah, kamu bakal dimanjain sama transaksi-transaksi yang bebas biaya. Bebas biaya tarik tunai, cek saldo, transfer antara BCA-BCA Syariah dan tarik tunai tanpa kartu di ATM BCA.\r\n \r\nYuk, segera download BSya dan nikmati segala kemudahannya.\r\n \r\nInformasi lebih lanjut, hubungi Halo BCA 1500 888 atau kunjungi www.bcasyariah.co.id',
  'descriptionHTML': 'Kenapa harus pake BSya? Yuk simak keunggulan BSya berikut ini:<br> <br>Fitur Lebih Lengkap<br>Kebutuhan transaksi kamu dapat terpenuhi dengan berbagai fitur, baik fitur transaksi finansial maupun transaksi non finansial.<br> <br>Nyaman<br>Cukup satu aplikasi untuk mengakses semua rekening kamu, kapanpun dan dimanapun. <br> <br>Aman<br>Transaksi lebih aman dengan proteksi maksimal yang dilengkapi dengan sistem biometrik, kode akses dan mPIN.<br> <br>Fitur BSya<br>• Pembukaan rekening online<br>• Transfer ke rekening BCA Syariah, Grup BCA, Virtual Account dan ke Bank Lain<br>• Pembelian dan pembayaran<br>• Mutasi rekening &amp; histori transaksi<br>• Informasi detail rekening deposito dan pembiayaan<br>• Pembayaran QRIS<br>• Top up e-Wallet<br>• Tarik tunai tanpa kartu, baik melalui fitur Cardless maupun eBranch<br>• Setoran biaya haji dan informasi RTJH<br>• Informasi rekening (cek saldo, mutasi rekening dan histori transaksi)<br>• Informasi jadwal sholat dan arah kiblat sesuai lokasi kamu<br>• Layanan contact center melalui Halo BCA<br> <br>Gak cuma itu.. Pembukaan rekening online di BSya juga dilengkapi dengan fitur autodebet Zakat. Ditambah lagi fitur-fitur yang memudahkan ibadah kamu seperti jadwal shalat dan arah kiblat. Jadi lebih berkah kan.. <br> <br>Info penting yang kamu perlu tahu! Jadi tim FrenS BCA Syariah, kamu bakal dimanjain sama transaksi-transaksi yang bebas biaya. Bebas biaya tarik tunai, cek saldo, transfer antara BCA-BCA Syariah dan tarik tunai tanpa kartu di ATM BCA.<br> <br>Yuk, segera download BSya dan nikmati segala kemudahannya.<br> <br>Informasi lebih lanjut, hubungi Halo BCA 1500 888 atau kunjungi www.bcasyariah.co.id',
  'developer': 'PT Bank BCA Syariah',
  'installs': '500.000+'},
 {'appId': 'com.bsm.activity2',
  'icon': 'https://play-lh.googleusercontent.com/37LouKJTsdX7DS28yN9LymTRIMmct9OATRPJrravKoSYKOCd6S6G3obfX_HQPm0pr54',
  'screenshots': ['https://play-lh.googleusercontent.com/jY62YXlls0t29O0zPwxPYbES1rT7sg9LnDFBWoiiDqp00rSxgSFqRjZQ_YQMkoox2w',
   'https://play-lh.googleusercontent.com/42sDJDil7u91dfOxmToKsxOw9AMCm0kcyMVQaoUZJPIOHSwTmXaSRg6w3iqRTnUfYOo',
   'https://play-lh.googleusercontent.com/NEg9sjdax6YT10PKfrcEclg_vz-cMSsD7y0qbCRJUi3usdz0xmt2TL25TnatrkKB2xIQ',
   'https://play-lh.googleusercontent.com/yOi_sibOtuzYcq9kR-S46bYblS60mJui5X0mjxVmChs8G0rv-fn9W7Okogea836iWoj9',
   'https://play-lh.googleusercontent.com/PNt7mh5ulXCx-R6UjHFY1c5DacE8doNXRnLgpVmVveVt_9H1gG2ix1tKkwn4MZTKIoyl',
   'https://play-lh.googleusercontent.com/dxPQE4tMPOu5S-_0OBT_Vj8AjUA9JqpZ7IFqs9MoMqlUSzMNEe5gliwqfeExoCA9Qw',
   'https://play-lh.googleusercontent.com/39uOeZ9ZDflTPvSJjb7K8Lt_GvWHJZuHV-9MHKH0hF80B4UEVYmogN0mRGC5FVJ9Ew',
   'https://play-lh.googleusercontent.com/neh-inUbFUFU4Ar1lgVMm7g4IrpI__GjxSCo0bkPeUf8LNmxaVp6nhuzWD9TAELfX2K3',
   'https://play-lh.googleusercontent.com/LZhxk_ScTl0U9MoMzkPvKQIRZBSoRTtLgPAq2JMZPAAG3efy9ujWVvx5UYsEg_zWpaKU'],
  'title': 'BSI Mobile',
  'score': 3.7492363,
  'genre': 'Keuangan',
  'price': 0,
  'free': True,
  'currency': 'IDR',
  'video': None,
  'videoImage': None,
  'description': 'BSI Mobile adalah salah satu saluran distribusi yang dimiliki oleh Bank Syariah Indonesia untuk mengakses rekening yang dimiliki nasabah dengan menggunakan teknologi 3G/4G/5G dan WIFI melalui smartphone.\r\n\r\nFitur:\r\n•\tInfo rekening (informasi saldo, mutasi, dan informasi portofolio)\r\n•\tTransfer (pindah buku, online, SKN, QRIS)\r\n•\tPembayaran (PLN, telepon/HP, akademik, institusi, tiket, asuransi, zakat/infaq, BPJS, MPN, PDAM, Internet/TV Kabel, dan E-commerce)\r\n•\tPembelian (voucher HP, PLN prabayar, E-money, Paket Data, Top Up EWallet, Aqiqah, Streaming Video & Musik, Kartu Debit OTP)\r\n•\tBuka rekening online\r\n•\tE-mas\r\n•\tTarik Tunai Tanpa Kartu\r\n•\tBSI Keyboard\r\n•\tTransaksi Terjadwal\r\n•\tAkses Menu Favorit\r\n•\tUpdate lokasi ATM dan Cabang\r\n•\tPenyimpan data transaksi favorit\r\n•\tShare aktivitas ke sosial media\r\n•\tJadwal shalat dan kalimat inspiratif\r\n•\tAkses sosial media Bank Syariah Indonesia\r\n•\tAkses langsung Bank Syariah Indonesia Call 14040\r\n•\tInformasi produk dan promo Bank Syariah Indonesia\r\n•\tNotifikasi detil transaksi ke email yang didaftarkan\r\n•\tBukti transaksi otomatis tersimpan di kotak masuk\r\n•\tPenambahan biller pembayaran dan pembelian\r\n•\tMenu Rate Mata Uang Asing\r\n•\tPortfolio Nasabah\r\n•\tPermintaan ulang kode aktivasi\r\n•\tDigital Wakaf\r\n\r\nRegistrasi:\r\n1.\tProses Pendaftaran/Registrasi \r\na.\tNasabah bisa melakukan registrasi BSI Mobile secara mandiri menggunakan verifikasi Face Recognition ataupun melalui Kantor Cabang, ATM BSI, dan Bank Syariah Indonesia Call 14040.\r\nb.\tSetelah registrasi berhasil, nasabah akan menerima SMS yang berisi kode aktivasi.\r\n\r\n2.\tProses Download \r\nUntuk ponsel dengan Android, IOS\r\nGoogle Play Store, App Store dengan keyword ‘BSI Mobile’.\r\nPastikan aplikasi BSI Mobile offered by / publisher / by PT Bank Syariah Indonesia, Tbk.\r\n\r\n3.\tProses Aktivasi\r\nNasabah meng-input nomor ponsel dan kode aktivasi yang didapat dari cabang pada saat pendaftaran/registrasi.\r\n\r\nInformasi lebih lanjut, kunjungi Bank Syariah Indonesia terdekat atau hubungi:\r\nBank Syariah Indonesia Call 14040. \r\nwww.bankbsi.co.id',
  'descriptionHTML': 'BSI Mobile adalah salah satu saluran distribusi yang dimiliki oleh Bank Syariah Indonesia untuk mengakses rekening yang dimiliki nasabah dengan menggunakan teknologi 3G/4G/5G dan WIFI melalui smartphone.<br><br>Fitur:<br>•\tInfo rekening (informasi saldo, mutasi, dan informasi portofolio)<br>•\tTransfer (pindah buku, online, SKN, QRIS)<br>•\tPembayaran (PLN, telepon/HP, akademik, institusi, tiket, asuransi, zakat/infaq, BPJS, MPN, PDAM, Internet/TV Kabel, dan E-commerce)<br>•\tPembelian (voucher HP, PLN prabayar, E-money, Paket Data, Top Up EWallet, Aqiqah, Streaming Video &amp; Musik, Kartu Debit OTP)<br>•\tBuka rekening online<br>•\tE-mas<br>•\tTarik Tunai Tanpa Kartu<br>•\tBSI Keyboard<br>•\tTransaksi Terjadwal<br>•\tAkses Menu Favorit<br>•\tUpdate lokasi ATM dan Cabang<br>•\tPenyimpan data transaksi favorit<br>•\tShare aktivitas ke sosial media<br>•\tJadwal shalat dan kalimat inspiratif<br>•\tAkses sosial media Bank Syariah Indonesia<br>•\tAkses langsung Bank Syariah Indonesia Call 14040<br>•\tInformasi produk dan promo Bank Syariah Indonesia<br>•\tNotifikasi detil transaksi ke email yang didaftarkan<br>•\tBukti transaksi otomatis tersimpan di kotak masuk<br>•\tPenambahan biller pembayaran dan pembelian<br>•\tMenu Rate Mata Uang Asing<br>•\tPortfolio Nasabah<br>•\tPermintaan ulang kode aktivasi<br>•\tDigital Wakaf<br><br>Registrasi:<br>1.\tProses Pendaftaran/Registrasi <br>a.\tNasabah bisa melakukan registrasi BSI Mobile secara mandiri menggunakan verifikasi Face Recognition ataupun melalui Kantor Cabang, ATM BSI, dan Bank Syariah Indonesia Call 14040.<br>b.\tSetelah registrasi berhasil, nasabah akan menerima SMS yang berisi kode aktivasi.<br><br>2.\tProses Download <br>Untuk ponsel dengan Android, IOS<br>Google Play Store, App Store dengan keyword ‘BSI Mobile’.<br>Pastikan aplikasi BSI Mobile offered by / publisher / by PT Bank Syariah Indonesia, Tbk.<br><br>3.\tProses Aktivasi<br>Nasabah meng-input nomor ponsel dan kode aktivasi yang didapat dari cabang pada saat pendaftaran/registrasi.<br><br>Informasi lebih lanjut, kunjungi Bank Syariah Indonesia terdekat atau hubungi:<br>Bank Syariah Indonesia Call 14040. <br>www.bankbsi.co.id',
  'developer': 'PT Bank Syariah Indonesia, Tbk.',
  'installs': '10.000.000+'},
 {'appId': 'co.id.bankbsi.superapp',
  'icon': 'https://play-lh.googleusercontent.com/q8urnk-GmiTavwxN-Jdfxs5_GsWjovOAJCfsD9LZlcP4IF6j3qmj2X3j80rriPJ1UA0i',
  'screenshots': ['https://play-lh.googleusercontent.com/LrCeoWR4_zuezwa5kRcMb00QfHqmqXowGKbIIfur_yhEg0ZDRpFHIWaH5GeXs32XBLKkMZCyH8sz4f_3FUBQ37M',
   'https://play-lh.googleusercontent.com/dbUvEBnCHWQSOv1crOvXFpjt0bN_aZnI0rGq-cSU8ukM1-Vk97M0b9oU81ovs1otFL_jUZO6KZeg5sdpFjmDdA',
   'https://play-lh.googleusercontent.com/R8UIAtdttsrFeRNJyFHhckSxnfG-MiZfCMlojw2Jcs_c7rNY49WwC9giuCK6KOylgpQLh9WqlyU1hgKV-_LQJQ',
   'https://play-lh.googleusercontent.com/BihC0OB8W4T28s3H2VsBgKNSHEQ-vAdPIf_RqEaKTOxlbXHOSGjurQDc2wP9oIFtdTkJUjqLguTegdpgLlLeXw',
   'https://play-lh.googleusercontent.com/i8hrV45v49clIHGLVsibnbtRa2FzS4qnsR53y-Iagm-bPU8QTmFIKNiKp59TTLmuebtLauzX2bJUFIGckJu_',
   'https://play-lh.googleusercontent.com/BD68PM29oqgj1YTDcgXDXaYLaUDcp4CIA3FWxzCNWuBmq9b07cn4AIUv4uXdRq6zcrFTHbjvgpkTHkI2ywl2pQ',
   'https://play-lh.googleusercontent.com/ImsCqOspLY7lpXI_Zu0R3T1VxF5nDcqLas6TSBTpFy1jaF54HvaT03TXVvdCUxe3E50CyWd2VBgw8Dkkdj_B_A',
   'https://play-lh.googleusercontent.com/q6OXLpbk77skLTEFEwb2SEKQ817pxE5G8S2oUCA4sGb-zQT3fE6_sZNQscNHQgVV1igPP_2xfsKrCLafbEKYfic',
   'https://play-lh.googleusercontent.com/ZVBTgmYVRI7-TaoAy9sZYQ0gWsfIOhcmQS9ZlLs7CrafVrndSHo7i-OHGXctscx0obZ5BPwUuhTGhDljBVnDaw',
   'https://play-lh.googleusercontent.com/aCBLg_i1JaR_qcJRQ-cQkb1ZfDeONNEsv-i2QG2NOBJlNkflzqXrMkJHq3DN7qN-i7pEsQwIPYoqaOD5aGUOvw',
   'https://play-lh.googleusercontent.com/BtcgFkPaBotoAxKiQXLUriu-AhwdeKXwrpjc5jET-6GVAkUwS-UTO2ugNqYQv8Yl5IrwEOjCi0ZcppuHOfgXaA',
   'https://play-lh.googleusercontent.com/0KdAKlbBoNFLmb1FZyOcJO7QW2foGkUehqTPN14WmdCvCiejG2sK_usQKjgK7zebiI3GSRH8bpYnE7vBGsaA7g',
   'https://play-lh.googleusercontent.com/ny6AwT0ezFs5-Dl2aVeTcyZZ_I98Oy-GqBZw1KWyoKvac76C2Vd5sH3l2b0sR8opknqnd1ks1S3Xe4yJ29Bw8Jk',
   'https://play-lh.googleusercontent.com/7rP1GdCy1_eDC-USMDGVq6LNWyTyeF2Qrt8nXS31Oop4PsB8i6G7sf3hqdLxF-hDucfrDTwS4TAkZj-lquIy',
   'https://play-lh.googleusercontent.com/hoQJbxc0Fxipdd64b9sY8XZtmRxRwdYkOF9lY_0v2m-X3EEQjaZqewpmdutPBUU70XI9mqXtnLsOWf7cBUuPxQ',
   'https://play-lh.googleusercontent.com/1kYrby3qyjPmb3tRjrOALcys6aaHxfVHy0rgyejttyYL-cDpJCgTHO3C2Tg0nCBPf2o9hIR-AVJpG3cZY2doVw',
   'https://play-lh.googleusercontent.com/ZVBTgmYVRI7-TaoAy9sZYQ0gWsfIOhcmQS9ZlLs7CrafVrndSHo7i-OHGXctscx0obZ5BPwUuhTGhDljBVnDaw',
   'https://play-lh.googleusercontent.com/aCBLg_i1JaR_qcJRQ-cQkb1ZfDeONNEsv-i2QG2NOBJlNkflzqXrMkJHq3DN7qN-i7pEsQwIPYoqaOD5aGUOvw',
   'https://play-lh.googleusercontent.com/BtcgFkPaBotoAxKiQXLUriu-AhwdeKXwrpjc5jET-6GVAkUwS-UTO2ugNqYQv8Yl5IrwEOjCi0ZcppuHOfgXaA',
   'https://play-lh.googleusercontent.com/0KdAKlbBoNFLmb1FZyOcJO7QW2foGkUehqTPN14WmdCvCiejG2sK_usQKjgK7zebiI3GSRH8bpYnE7vBGsaA7g',
   'https://play-lh.googleusercontent.com/ny6AwT0ezFs5-Dl2aVeTcyZZ_I98Oy-GqBZw1KWyoKvac76C2Vd5sH3l2b0sR8opknqnd1ks1S3Xe4yJ29Bw8Jk',
   'https://play-lh.googleusercontent.com/7rP1GdCy1_eDC-USMDGVq6LNWyTyeF2Qrt8nXS31Oop4PsB8i6G7sf3hqdLxF-hDucfrDTwS4TAkZj-lquIy',
   'https://play-lh.googleusercontent.com/hoQJbxc0Fxipdd64b9sY8XZtmRxRwdYkOF9lY_0v2m-X3EEQjaZqewpmdutPBUU70XI9mqXtnLsOWf7cBUuPxQ',
   'https://play-lh.googleusercontent.com/1kYrby3qyjPmb3tRjrOALcys6aaHxfVHy0rgyejttyYL-cDpJCgTHO3C2Tg0nCBPf2o9hIR-AVJpG3cZY2doVw',
   'https://play-lh.googleusercontent.com/lpMSAS2pmqh-hAHyZAeF4LKJoguQRNk6ADU1pIDGep52u5wSdHgmZ5xTYaWMlFB9Ab0'],
  'title': 'BYOND by BSI',
  'score': 3.5577226,
  'genre': 'Keuangan',
  'price': 0,
  'free': True,
  'currency': 'IDR',
  'video': 'https://www.youtube.com/embed/-Hz-mWhYIGA?vq=large&rel=0&autohide=1&showinfo=0',
  'videoImage': 'https://i.ytimg.com/vi/-Hz-mWhYIGA/hqdefault.jpg',
  'description': 'Saatnya bikin aktivitas perbankanmu jadi lebih mudah bersama BYOND by BSI.  \r\n \r\nAplikasi \u202fperbankan yang bisa penuhi beragam kebutuhan finansial, sosial, dan spiritualmu.\r\n \r\nMau buka tabungan, investasi, hingga pembiayaan kini semakin mudah!  \r\n \r\nPenuhi berbagai kebutuhan dan keinginanmu \u202fbareng BYOND by BSI.\r\n \r\nBYOND juga dilengkapi dengan fitur-fitur Islami yang akan mempermudah ibadahmu.\r\n\u202f\r\nDownload BYOND by BSI sekarang biar #SemuaJadiMudah',
  'descriptionHTML': 'Saatnya bikin aktivitas perbankanmu jadi lebih mudah bersama BYOND by BSI.  <br> <br>Aplikasi \u202fperbankan yang bisa penuhi beragam kebutuhan finansial, sosial, dan spiritualmu.<br> <br>Mau buka tabungan, investasi, hingga pembiayaan kini semakin mudah!  <br> <br>Penuhi berbagai kebutuhan dan keinginanmu \u202fbareng BYOND by BSI.<br> <br>BYOND juga dilengkapi dengan fitur-fitur Islami yang akan mempermudah ibadahmu.<br>\u202f<br>Download BYOND by BSI sekarang biar #SemuaJadiMudah',
  'developer': 'PT Bank Syariah Indonesia, Tbk.',
  'installs': '5.000.000+'},
 {'appId': 'com.jago.digitalBanking',
  'icon': 'https://play-lh.googleusercontent.com/G4j9T1IJNgt9JvhibKLF92i5m6epQ1JG12v5-qvEhXMsRhXYjK-RSPt2v0_SZh-j2aNtP_BmQOWKuWu0fnnv',

# Cek Tipe Data dan Panjang Data

In [3]:
#Mengecek tipe data Hasil
print(type(results))

#Mengecek panjang data Hasil
print(len(results))

<class 'list'>
10

# Menampung Hasil scraping ke variable baru bernama "app_id"

In [4]:

app_id = [elemen.get('appId') for elemen in results]
print(app_id)

['co.id.newmb.btnsyariah', 'id.co.bcasyariah.bsya', 'com.bsm.activity2', 'co.id.bankbsi.superapp', 'com.jago.digitalBanking', 'id.aladinbank.mobile', 'com.megasyariah', 'com.bankntbsyariah.mobilebanking', 'com.app.vioss4', 'co.id.bankbsi.qrismerchant']

# Menampung Hasil scraping ke Variable baru bernama "app_title"

In [10]:
app_title = [elemen.get('title') for elemen in results]
print(app_title)

['Bale Syariah By BSN', 'BSya by BCA Syariah', 'BSI Mobile', 'BYOND by BSI', 'Bank Jago/Jago Syariah', 'Aladin : Bank Syariah Digital', 'M-Syariah', 'Rimo By Bank NTB Syariah', 'BISA Mobile by KBBS', 'BYOND Merchant by BSI']

# Gunakan Fitur review_all dari Library Googleplay Scraper untuk ambil data Semua Review dan Libray Pandas untuk olah data

In [11]:
#Melakukan pencarian Semua Review yang ada di semua variable app_id
from google_play_scraper import reviews_all
import pandas as pd

#buat Data Frame  Kosong
data_itegrasi = pd.DataFrame()

#Proses Ekstrasi Review
for id, title in zip(app_id, app_title):
    reviews = reviews_all (
        id,
        sleep_milliseconds=100,
        lang='id',
        country='id'
    )

  #Ubah ke Data frame
    data_reviews = pd.DataFrame(reviews)

  #Buat Kolom Baru Sebagai Penanda
    data_reviews['app_id'] = id
    data_reviews['app_title'] = title

  ##Proses Append Data
    data_itegrasi = pd.concat([data_itegrasi, data_reviews])

/tmp/ipykernel_5393/2949561371.py:25: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data_itegrasi = pd.concat([data_itegrasi, data_reviews])

# Cek Data Hasil Review

In [12]:
display(data_itegrasi)

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,app_id,app_title
0,bf7e3e86-7e8a-41b1-9282-9dcd67e4c302,Pandawa Lima,https://play-lh.googleusercontent.com/a-/ALV-U...,Tolong ditambahkan lagi fitur2nya dan tambahka...,1,1,2.0.2,2026-05-08 20:56:30,None,NaT,2.0.2,co.id.newmb.btnsyariah,Bale Syariah By BSN
1,bd391730-ce48-4de7-8811-6efa538d67e9,syahri Romadhon,https://play-lh.googleusercontent.com/a-/ALV-U...,manaa sii mau login gabisa pulsa abiss ngirim ...,1,0,None,2026-05-08 13:32:13,None,NaT,None,co.id.newmb.btnsyariah,Bale Syariah By BSN
2,a65af3ca-c06f-4c95-ac56-15973b5ba996,irvan hizbullah,https://play-lh.googleusercontent.com/a-/ALV-U...,Aplikasinya ringan dan komplit,5,0,2.0.1,2026-05-07 10:13:16,None,NaT,2.0.1,co.id.newmb.btnsyariah,Bale Syariah By BSN
3,72613f08-532a-4b27-bbe2-79744f906948,adnanramadhan,https://play-lh.googleusercontent.com/a/ACg8oc...,inii gimana min gabisa masukin kode otp ah elah,1,0,2.0.1,2026-05-07 05:07:25,None,NaT,2.0.1,co.id.newmb.btnsyariah,Bale Syariah By BSN
4,7d58b783-b4c9-4350-bf02-d02e30dd715d,jefferson lumentut,https://play-lh.googleusercontent.com/a-/ALV-U...,tetap stag di verifikasi.. gimana sih aplikasi...,1,0,2.0.1,2026-05-07 01:50:40,None,NaT,2.0.1,co.id.newmb.btnsyariah,Bale Syariah By BSN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,ecfe8539-f900-4c61-a644-896ecafb278e,Awi Aja,https://play-lh.googleusercontent.com/a/ACg8oc...,versi ini lebih cepat dari versi sebelumnya......,5,5,1.0.0.12,2025-05-14 06:22:12,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI
119,a0edf600-cf23-4614-a346-f6016233c5ea,Wastim Cah Brebes (Mang oblag),https://play-lh.googleusercontent.com/a/ACg8oc...,"aplikasi sudah bisa masuk/log in lagi,( tadiny...",4,6,1.0.0.12,2025-05-14 03:30:06,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI
120,828c506e-6771-4b2a-896a-03213cd226c6,Salihin Ahmed,https://play-lh.googleusercontent.com/a-/ALV-U...,harus unstal terus baru bisa cek,1,6,1.0.0.12,2025-05-13 22:18:49,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI
121,9cc0b0a1-1db8-41c0-82bc-a3028c417dc6,muhammad afif amirillah,https://play-lh.googleusercontent.com/a/ACg8oc...,very good,5,3,1.0.0.12,2025-05-11 08:37:34,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI
122,50781ff6-a5da-4ee6-8716-f2175db04afd,Gian,https://play-lh.googleusercontent.com/a-/ALV-U...,Bagus,5,2,1.0.0.12,2025-05-10 07:57:47,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI

# Cek Informasi Umum Pada Data

In [13]:
data_itegrasi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 292896 entries, 0 to 122
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   reviewId              292896 non-null  object
 1   userName              292896 non-null  object
 2   userImage             292896 non-null  object
 3   content               292895 non-null  object
 4   score                 292896 non-null  int64
 5   thumbsUpCount         292896 non-null  int64
 6   reviewCreatedVersion  238038 non-null  object
 7   at                    292896 non-null  datetime64[ns]
 8   replyContent          252350 non-null  object
 9   repliedAt             252350 non-null  datetime64[ns]
 10  appVersion            238038 non-null  object
 11  app_id                292896 non-null  object
 12  app_title             292896 non-null  object
dtypes: datetime64[ns](2), int64(2), object(9)
memory usage: 31.3+ MB

# Cek Jumlah  Review setiap aplikasi

In [14]:
data_itegrasi['app_title'].value_counts()

app_title
BSI Mobile                       128757
Bank Jago/Jago Syariah            69665
BYOND by BSI                      57813
Aladin : Bank Syariah Digital     30386
M-Syariah                          2157
BSya by BCA Syariah                1507
Bale Syariah By BSN                1076
Rimo By Bank NTB Syariah           1034
BISA Mobile by KBBS                 378
BYOND Merchant by BSI               123
Name: count, dtype: int64

# Tambah metadata Waktu Penarikan/Extract data

In [16]:
from datetime import datetime
data_itegrasi['extract_date'] = datetime.now()

display(data_itegrasi)

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,app_id,app_title,extract_date
0,bf7e3e86-7e8a-41b1-9282-9dcd67e4c302,Pandawa Lima,https://play-lh.googleusercontent.com/a-/ALV-U...,Tolong ditambahkan lagi fitur2nya dan tambahka...,1,1,2.0.2,2026-05-08 20:56:30,None,NaT,2.0.2,co.id.newmb.btnsyariah,Bale Syariah By BSN,2026-05-12 08:43:47.477178
1,bd391730-ce48-4de7-8811-6efa538d67e9,syahri Romadhon,https://play-lh.googleusercontent.com/a-/ALV-U...,manaa sii mau login gabisa pulsa abiss ngirim ...,1,0,None,2026-05-08 13:32:13,None,NaT,None,co.id.newmb.btnsyariah,Bale Syariah By BSN,2026-05-12 08:43:47.477178
2,a65af3ca-c06f-4c95-ac56-15973b5ba996,irvan hizbullah,https://play-lh.googleusercontent.com/a-/ALV-U...,Aplikasinya ringan dan komplit,5,0,2.0.1,2026-05-07 10:13:16,None,NaT,2.0.1,co.id.newmb.btnsyariah,Bale Syariah By BSN,2026-05-12 08:43:47.477178
3,72613f08-532a-4b27-bbe2-79744f906948,adnanramadhan,https://play-lh.googleusercontent.com/a/ACg8oc...,inii gimana min gabisa masukin kode otp ah elah,1,0,2.0.1,2026-05-07 05:07:25,None,NaT,2.0.1,co.id.newmb.btnsyariah,Bale Syariah By BSN,2026-05-12 08:43:47.477178
4,7d58b783-b4c9-4350-bf02-d02e30dd715d,jefferson lumentut,https://play-lh.googleusercontent.com/a-/ALV-U...,tetap stag di verifikasi.. gimana sih aplikasi...,1,0,2.0.1,2026-05-07 01:50:40,None,NaT,2.0.1,co.id.newmb.btnsyariah,Bale Syariah By BSN,2026-05-12 08:43:47.477178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,ecfe8539-f900-4c61-a644-896ecafb278e,Awi Aja,https://play-lh.googleusercontent.com/a/ACg8oc...,versi ini lebih cepat dari versi sebelumnya......,5,5,1.0.0.12,2025-05-14 06:22:12,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI,2026-05-12 08:43:47.477178
119,a0edf600-cf23-4614-a346-f6016233c5ea,Wastim Cah Brebes (Mang oblag),https://play-lh.googleusercontent.com/a/ACg8oc...,"aplikasi sudah bisa masuk/log in lagi,( tadiny...",4,6,1.0.0.12,2025-05-14 03:30:06,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI,2026-05-12 08:43:47.477178
120,828c506e-6771-4b2a-896a-03213cd226c6,Salihin Ahmed,https://play-lh.googleusercontent.com/a-/ALV-U...,harus unstal terus baru bisa cek,1,6,1.0.0.12,2025-05-13 22:18:49,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI,2026-05-12 08:43:47.477178
121,9cc0b0a1-1db8-41c0-82bc-a3028c417dc6,muhammad afif amirillah,https://play-lh.googleusercontent.com/a/ACg8oc...,very good,5,3,1.0.0.12,2025-05-11 08:37:34,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI,2026-05-12 08:43:47.477178
122,50781ff6-a5da-4ee6-8716-f2175db04afd,Gian,https://play-lh.googleusercontent.com/a-/ALV-U...,Bagus,5,2,1.0.0.12,2025-05-10 07:57:47,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI,2026-05-12 08:43:47.477178

# Ubah semua kolom terlebih dahulu ke Lowercase sebelum disimpan di Database

In [18]:
from IPython.core.interactiveshell import dis
data_itegrasi.columns = data_itegrasi.columns.str.lower()

display(data_itegrasi)

,reviewid,username,userimage,content,score,thumbsupcount,reviewcreatedversion,at,replycontent,repliedat,appversion,app_id,app_title,extract_date
0,bf7e3e86-7e8a-41b1-9282-9dcd67e4c302,Pandawa Lima,https://play-lh.googleusercontent.com/a-/ALV-U...,Tolong ditambahkan lagi fitur2nya dan tambahka...,1,1,2.0.2,2026-05-08 20:56:30,None,NaT,2.0.2,co.id.newmb.btnsyariah,Bale Syariah By BSN,2026-05-12 08:43:47.477178
1,bd391730-ce48-4de7-8811-6efa538d67e9,syahri Romadhon,https://play-lh.googleusercontent.com/a-/ALV-U...,manaa sii mau login gabisa pulsa abiss ngirim ...,1,0,None,2026-05-08 13:32:13,None,NaT,None,co.id.newmb.btnsyariah,Bale Syariah By BSN,2026-05-12 08:43:47.477178
2,a65af3ca-c06f-4c95-ac56-15973b5ba996,irvan hizbullah,https://play-lh.googleusercontent.com/a-/ALV-U...,Aplikasinya ringan dan komplit,5,0,2.0.1,2026-05-07 10:13:16,None,NaT,2.0.1,co.id.newmb.btnsyariah,Bale Syariah By BSN,2026-05-12 08:43:47.477178
3,72613f08-532a-4b27-bbe2-79744f906948,adnanramadhan,https://play-lh.googleusercontent.com/a/ACg8oc...,inii gimana min gabisa masukin kode otp ah elah,1,0,2.0.1,2026-05-07 05:07:25,None,NaT,2.0.1,co.id.newmb.btnsyariah,Bale Syariah By BSN,2026-05-12 08:43:47.477178
4,7d58b783-b4c9-4350-bf02-d02e30dd715d,jefferson lumentut,https://play-lh.googleusercontent.com/a-/ALV-U...,tetap stag di verifikasi.. gimana sih aplikasi...,1,0,2.0.1,2026-05-07 01:50:40,None,NaT,2.0.1,co.id.newmb.btnsyariah,Bale Syariah By BSN,2026-05-12 08:43:47.477178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,ecfe8539-f900-4c61-a644-896ecafb278e,Awi Aja,https://play-lh.googleusercontent.com/a/ACg8oc...,versi ini lebih cepat dari versi sebelumnya......,5,5,1.0.0.12,2025-05-14 06:22:12,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI,2026-05-12 08:43:47.477178
119,a0edf600-cf23-4614-a346-f6016233c5ea,Wastim Cah Brebes (Mang oblag),https://play-lh.googleusercontent.com/a/ACg8oc...,"aplikasi sudah bisa masuk/log in lagi,( tadiny...",4,6,1.0.0.12,2025-05-14 03:30:06,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI,2026-05-12 08:43:47.477178
120,828c506e-6771-4b2a-896a-03213cd226c6,Salihin Ahmed,https://play-lh.googleusercontent.com/a-/ALV-U...,harus unstal terus baru bisa cek,1,6,1.0.0.12,2025-05-13 22:18:49,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI,2026-05-12 08:43:47.477178
121,9cc0b0a1-1db8-41c0-82bc-a3028c417dc6,muhammad afif amirillah,https://play-lh.googleusercontent.com/a/ACg8oc...,very good,5,3,1.0.0.12,2025-05-11 08:37:34,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI,2026-05-12 08:43:47.477178
122,50781ff6-a5da-4ee6-8716-f2175db04afd,Gian,https://play-lh.googleusercontent.com/a-/ALV-U...,Bagus,5,2,1.0.0.12,2025-05-10 07:57:47,None,NaT,1.0.0.12,co.id.bankbsi.qrismerchant,BYOND Merchant by BSI,2026-05-12 08:43:47.477178

# **Load Data Ke Google BigQuery**

In [19]:
#Import Library Google Colab dan lain-lainnya
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq

#Autentifikasi User terlebih dahulu
auth.authenticate_user()
print('Authenticated')

Authenticated

# Buat DataSet Baru bernama review_gplay_bank_syariah

In [21]:
from google.cloud.bigquery import dataset
#Inisialisasi project_id
project_id = 'fullstack-bangalore-494812'
client = bigquery.Client( project = project_id)

#Buat DataSet baru
dataset_id = 'review_gplay_bank_syariah'
dataset_ref = bigquery.Dataset(f'{project_id}.{dataset_id}')
dataset = client.create_dataset(dataset_ref, exists_ok=True)

# Proses Load Data ke DataSet baru

In [22]:
to_gbq(
  data_itegrasi,
  destination_table = f'{dataset_id}.review_all_bank_syariah',
  project_id = project_id,
  if_exists = 'append')

100%|██████████| 1/1 [00:00<00:00, 12300.01it/s]

#**Jika hanya Melakukan Review hanya satu aplikasi saja**

In [7]:
#Melakukan pencarian Semua Review yang ada di aplikasi mobile "Bank BSI SupperApp"
from google_play_scraper import reviews_all
import pandas as pd

review1 = reviews_all (
    'co.id.bankbsi.superapp',
    sleep_milliseconds=100,
    lang='id',
    country='id'
)

#Menampilkan Hasilnya
display(review1)

[{'reviewId': '86c5297f-cbbd-43c2-9653-a1061ad6f661',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'katanya bisa daftar lewat online tapi kenapa saat pengajuan error mulu. gimana sih tolong tindak lanjuti',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 11, 8, 17, 15),
  'replyContent': 'Assalamualaikum Ibu Cece. Mohon maaf atas ketidaknyamanannya, jika terdapat kendala atau keluhan, mohon untuk melakukan konfirmasi melalui Kantor Cabang BSI terdekat atau menghubungi BSI Call di 14040. Untuk informasi lebih lanjut dapat menghubungi Email kami di contactus@bankbsi.co.id Terima kasih. Wassalamualaikum -Siska',
  'repliedAt': datetime.datetime(2026, 5, 11, 8, 22, 51),
  'appVersion': '1.2.2'},
 {'reviewId': 'f4a34f38-9464-4b0e-bb53-c51821e3cf37',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'Mantul Aplikasi Online BSI',
  'score': 5,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': None,
  'at': datetime.datetime(2026, 5, 11, 7, 54, 48),
  'replyContent': 'Assalamualaikum Bapak Karsono, terima kasih atas apresiasinya. Bank Syariah Indonesia akan terus berupaya memberikan yang terbaik bagi nasabahnya. Apabila ada kritik dan saran lainnya dapat disampaikan melalui email resmi kami di contactus@bankbsi.co.id. Terima kasih, Wassalamualaikum -Tama\n',
  'repliedAt': datetime.datetime(2026, 5, 11, 8, 5, 29),
  'appVersion': None},
 {'reviewId': 'cafee66b-df42-42f8-815e-05874c980a98',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'saya tdk suka apk bank ini sll update...ribet...',
  'score': 3,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.1',
  'at': datetime.datetime(2026, 5, 11, 7, 37, 28),
  'replyContent': 'Assalamualaikum Bapak Duradji, mohon maaf dan terima kasih atas saran yang diberikan, hal ini akan menjadi masukan berharga untuk pengembangan BYOND by BSI kedepannya. Apabila ada saran atau informasi lainnya, maka dapat disampaikan melalui Layanan BSI Call 14040 atau Email kami di contactus@bankbsi.co.id Terima kasih. Wassalamualaikum -Eliza',
  'repliedAt': datetime.datetime(2026, 5, 11, 7, 46, 26),
  'appVersion': '1.2.1'},
 {'reviewId': '46d9ddb6-4df1-431b-965b-0362e5015ea5',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'Ini beneran gak bisa pelaporan transaksi? percuma ada fitur tapi tidak bisa digunakan terus. saya transaksi di ATM tarik tunai 100K, saldo saya terpotong, namun uang tidak keluar. giliran pelaporan transaksi malah gak bisa',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 11, 7, 30, 12),
  'replyContent': 'Assalamualaikum Bapak Abdussalam, Mohon maaf atas ketidaknyamanannya. Terkait gagal transaksi tarik tunai, pelaporannya saat ini hanya melalui BSI Call 14040 atau Kantor Cabang BSI terdekat. Informasi lebih lanjut dapat menghubungi kami melalui email resmi BSI di contactus@bankbsi.co.id. Terima kasih, Wassalamualaikum - Nina',
  'repliedAt': datetime.datetime(2026, 5, 11, 7, 33, 20),
  'appVersion': '1.2.2'},
 {'reviewId': 'de9d502c-8ed5-49fa-9f8a-166ac34095f7',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'Kenapa developer mode dianggap bermasalah, tidak ada opsi menolak notofikasi adzan, kami udah punya aplikasi sendiri',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': None,
  'at': datetime.datetime(2026, 5, 11, 7, 29, 46),
  'replyContent': 'Assalamualaikum Bapak Angga, mohon maaf atas ketidaknyamanannya. Terkait hal tersebut untuk meningkatkan keamanan dan kenyamanan bertransaksi. Untuk informasi lebih lanjut dapat menghubungi BSI Call 14040 atau Email kami di contactus@bankbsi.co.id Terima kasih. Wassalamualaikum -Siska',
  'repliedAt': datetime.datetime(2026, 5, 11, 7, 30, 56),
  'appVersion': None},
 {'reviewId': '2747613b-de86-44a8-9a49-eaf2d12519ce',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'Ini vendor apps niat gak sih... LEMOT kelewatan. Masa sekelas bank kalah cepat sama DANA Indonesia.',
  'score': 5,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 11, 7, 4, 42),
  'replyContent': 'Assalamualaikum Bapak Hengki, mohon maaf dan terima kasih atas saran yang diberikan, hal ini akan menjadi masukan berharga untuk pengembangan BYOND by BSI kedepannya. Apabila ada saran atau keluhan lainnya, maka dapat disampaikan melalui Layanan BSI Call 14040 atau Email kami di contactus@bankbsi.co.id Terima kasih. Wassalamualaikum -Eliza\n',
  'repliedAt': datetime.datetime(2026, 5, 11, 7, 10, 24),
  'appVersion': '1.2.2'},
 {'reviewId': 'a6921834-a6a2-4eca-96f9-2299f5a58310',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'buruk. banyak perbaikan dan pelayanan nya kurang bagus',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 11, 6, 45, 5),
  'replyContent': 'Assalamualaikum Ibu Qila, mohon maaf dan terima kasih atas saran yang diberikan, hal ini akan menjadi masukan berharga untuk pengembangan BYOND by BSI kedepannya. Apabila ada saran atau keluhan lainnya, maka dapat disampaikan melalui Layanan BSI Call 14040 atau Email kami di contactus@bankbsi.co.id Terima kasih. Wassalamualaikum -Eliza',
  'repliedAt': datetime.datetime(2026, 5, 11, 6, 48, 48),
  'appVersion': '1.2.2'},
 {'reviewId': '4df5bba4-12fb-44ab-b619-8ca772679e9b',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'halo, kenapa ya tiap mau bayar QRIS selalu gagal atu tidak bisa masukin nominal atu mau ngetik angka selalu gak bisa....?',
  'score': 5,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 11, 6, 31, 48),
  'replyContent': 'Assalamualaikum Ibu Nur Zaini. Mohon maaf atas ketidaknyamanannya, terkait kendala transaksinya mohon dapat konfirmasi dengan menghubungi BSI Call di 14040. Untuk informasi lebih lanjut dapat menghubungi Email kami di contactus@bankbsi.co.id Terima kasih. Wassalamualaikum -Siska',
  'repliedAt': datetime.datetime(2026, 5, 11, 6, 34, 22),
  'appVersion': '1.2.2'},
 {'reviewId': '6219136e-1622-45f3-9a1f-433ba7041502',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'setoran awal 150.000 kok masuk cuma 100.000 ya?',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 11, 1, 59, 35),
  'replyContent': 'Assalamualaikum Bapak Ubaidillah, mohon maaf atas ketidaknyamanannya. Terkait hal tersebut dikhawatirkan terdapat saldo minimal yang tidak terlihat, untuk informasi detailnya silakan menghubungi layanan BSI Call 14040, Kantor Cabang BSI terdekat atau dapat menghubungi Email kami di contactus@bankbsi.co.id Terima kasih, Wassalamualaikum -Eliza\n',
  'repliedAt': datetime.datetime(2026, 5, 11, 2, 4, 59),
  'appVersion': '1.2.2'},
 {'reviewId': '5050f37b-836f-4682-b801-3326e5846839',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'aplikasi sampah.. berkali kali transaksi qris nyangkut terus dana nya.. saldo berkurang dan transaksi gagal.. nunggu duit balik sampe berminggu-minggu.. nelp cs pun ga ada solusi cuma suruh nunggu',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 11, 1, 23, 36),
  'replyContent': 'Assalamualaikum Bapak Ichwan, mohon maaf atas ketidaknyamanannya. Mengenai keluhan dan kendala yang dialami, mohon berkenan untuk menghubungi layanan BSI Call 14040 atau melalui email resmi BSI di contactus@bankbsi.co.id. Terima kasih, Wassalamualaikum - Nina',
  'repliedAt': datetime.datetime(2026, 5, 11, 1, 25, 24),
  'appVersion': '1.2.2'},
 {'reviewId': '89cf67bf-2c66-47d0-8b7c-9bde6871aadb',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'senang banget transaksi makin mudah menggunakan byond tidak perlu jauh jauh untuk transfer',
  'score': 5,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': None,
  'at': datetime.datetime(2026, 5, 11, 1, 7, 30),
  'replyContent': 'Assalamualaikum Ibu Virda, terima kasih atas apresiasi yang diberikan. BSI akan terus melakukan peningkatan fitur menarik untuk memudahkan nasabahnya dalam proses transaksi menggunakan BYOND by BSI. Apabila terdapat saran lainnya dapat disampaikan melalui email resmi kami di contactus@bankbsi.co.id. Terima kasih, Wassalamualaikum - Nina',
  'repliedAt': datetime.datetime(2026, 5, 11, 1, 9, 33),
  'appVersion': None},
 {'reviewId': '8b0a90a2-274f-47f0-a9a3-62a498e5dc8c',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'susah banget daftarnya, mana kalo gagal langsung ulang dari awal lagiiiii',
  'score': 2,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 11, 0, 2, 41),
  'replyContent': 'Assalamualaikum Bapak Nazam, mohon maaf atas ketidaknyamanannya. Terkait kendala tersebut, pastikan untuk pengisian data sudah sesuai dengan yang terdaftar di BSI. Jika masih mengalami kendala, mohon kesediaannya untuk menghubungi layanan BSI Call 14040 atau melalui email resmi kami di contactus@bankbsi.co.id. Terima kasih, Wassalamualaikum - Nina',
  'repliedAt': datetime.datetime(2026, 5, 11, 0, 4, 50),
  'appVersion': '1.2.2'},
 {'reviewId': '5f022a3e-085b-48fb-94f1-86e3d6f4aa61',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': '"ajukan laporan" lambat sekali responnya. aku tf uang, uang nya tidak masuk tapi saldonya terpotong..',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 10, 22, 40, 33),
  'replyContent': 'Assalamualaikum Bapak/Ibu Legal Standing, mohon maaf atas ketidaknyamanannya, terkait hal ini mohon kesediaannya untuk menghubungi layanan BSI Call 14040 atau melalui email resmi kami di contactus@bankbsi.co.id\nTerima kasih. Wassalamualaikum-Edo',
  'repliedAt': datetime.datetime(2026, 5, 10, 22, 45, 48),
  'appVersion': '1.2.2'},
 {'reviewId': '80108539-c71c-45b5-b0d8-1a2f039cfb61',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'min, tolong tambahin pemberitahuan kalo ada uang masuk, masa gk ada notif sama sekali, apl yg lain aja ada motifnya, kembangkanlah min',
  'score': 3,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 10, 22, 15, 47),
  'replyContent': 'Assalamualaikum Bapak Jawzhar, terima kasih atas masukan dan saran yang diberikan, hal ini akan menjadi masukan berharga untuk perbaikan kami kedepannya. Apabila ada saran atau informasi lainnya maka dapat disampaikan melalui layanan BSI Call 14040 atau melalui email resmi kami di contactus@bankbsi.co.id\nTerima kasih. Wassalamualaikum-Edo',
  'repliedAt': datetime.datetime(2026, 5, 10, 22, 19, 10),
  'appVersion': '1.2.2'},
 {'reviewId': '0432f9fa-1fa9-4579-8804-a452bcf263a4',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'saya top up 400 knpa yg masuk hanya 350 tolong bantu kembalikan',
  'score': 5,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': None,
  'at': datetime.datetime(2026, 5, 10, 21, 47, 45),
  'replyContent': 'Assalamualaikum Kak Bapak Jariah dhedhe. Mohon maaf atas ketidaknyamanannya, dapat kami informasikan untuk rekening reguler memang terdapat saldo minimum sebesar Rp50.000. Detail informasi dapat menghubungi email resmi kami di contactus@bankbsi.co.id. Terima kasih, Wassalamualaikum -Edo',
  'repliedAt': datetime.datetime(2026, 5, 10, 22, 11, 21),
  'appVersion': None},
 {'reviewId': 'ac3ed7e2-4667-4dc0-8491-d606524b39dd',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'apk ini kenapa sekarang kok tidak bisa sama sekali dan knapa juga di mintai info lokasi tidak seperti apk lainya coba tidak pakai info lokasi mungkin agak ringan dan gak sering erro seperti ini hampir tidak bisa hp ram 8 kok susah buka apk ini tolong systemnya di ringankan supaya kinerja apk ini lebih ringan dan cepat karena dngan adanya apk ini kita bisa cek tabungan kita sudah sering terjadi seperti ini tidak bisa kbuka meskipun sinyal sngat kuat misalkan ada bsi lite mungkin bisa ringan cepat',
  'score': 5,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': None,
  'at': datetime.datetime(2026, 5, 10, 20, 45, 19),
  'replyContent': 'Assalamualaikum Bapak Er Vcx. Mohon maaf atas ketidaknyamanannya. BYOND by BSI terdapat waktu salat maka memerlukan lokasi saat ini dan dipastikan saat menggunakan BYOND by BSI jaringan yang digunakan stabil. Jika terkendala, dapat menghubungi layanan BSI Call 14040 atau email resmi kami di contactus@bankbsi.co.id\nTerima kasih. Wassalamualaikum-Edo',
  'repliedAt': datetime.datetime(2026, 5, 10, 20, 48, 9),
  'appVersion': None},
 {'reviewId': 'c9c3f5b7-a10b-4ff4-9137-a42328ff040f',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'ribet gx bisa kebuka aplikasinya',
  'score': 3,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 10, 18, 44, 42),
  'replyContent': 'Assalamualaikum Bapak Aan Kusdian. Mohon maaf atas ketidaknyamanannya. Terkait hal tersebut kami sarankan agar dipastikan jaringan data yang digunakan stabil. Jika masih mengalami kendala, mohon berkenan untuk menghubungi layanan BSI Call 14040 atau melalui email resmi kami di contactus@bankbsi.co.id\nTerima kasih. Wassalamualaikum-Edo',
  'repliedAt': datetime.datetime(2026, 5, 10, 18, 50, 44),
  'appVersion': '1.2.2'},
 {'reviewId': '63f67d47-6415-4fb7-8757-86b03f456df9',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'keren sih ini apknya sangat mudah di gunakan kapanpun dan di manapun, no coment',
  'score': 5,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 10, 18, 6, 40),
  'replyContent': 'Assalamualaikum Bapak Sahrul Irawan, terima kasih atas apresiasi yang diberikan kepada kami. Apabila ada saran atau informasi lainnya maka dapat disampaikan melalui layanan BSI Call 14040 atau melalui email resmi kami di contactus@bankbsi.co.id\nTerima kasih. Wassalamualaikum-Edo',
  'repliedAt': datetime.datetime(2026, 5, 10, 18, 11, 14),
  'appVersion': '1.2.2'},
 {'reviewId': 'a3c6ef8a-4534-4223-8a70-635a21b871ef',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'Penggunaan mudah ga ribet samsek, daftarnya juga gampang dan ini worth it banget sih suka',
  'score': 5,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 10, 17, 29, 28),
  'replyContent': 'Assalamualaikum Bapak Febri, terima kasih atas apresiasi yang diberikan kepada kami. Apabila ada saran atau informasi lainnya maka dapat disampaikan melalui layanan BSI Call 14040 atau melalui email resmi kami di contactus@bankbsi.co.id\nTerima kasih. Wassalamualaikum-Edo',
  'repliedAt': datetime.datetime(2026, 5, 10, 17, 37, 15),
  'appVersion': '1.2.2'},
 {'reviewId': '58e1f465-7e79-4acc-bb55-8ded04b5cd0c',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'punya sya gak bisa kirim uang saldo .apakah saldo 30000 gak bisa ditarik',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 10, 17, 7, 16),
  'replyContent': 'Assalamualaikum Bapak Yogi, mohon maaf atas ketidaknyamanannya, terkait hal ini mohon kesediaannya untuk menghubungi layanan BSI Call 14040 atau melalui email resmi kami di contactus@bankbsi.co.id\nTerima kasih. Wassalamualaikum-Edo',
  'repliedAt': datetime.datetime(2026, 5, 10, 17, 11, 20),
  'appVersion': '1.2.2'},
 {'reviewId': '8592eb09-be00-4ef3-8bc7-22c5f2e57f59',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'ngelag parah',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 10, 14, 56, 26),
  'replyContent': 'Assalamualaikum Bapak asep, mohon maaf atas ketidaknyamanannya. Terkait kendala yang dialami, mohon kesediaannya untuk menghubungi layanan BSI Call 14040 atau Kantor Cabang BSI terdekat, untuk informasi lebih lanjut dapat menghubungi melalui email resmi kami di contactus@bankbsi.co.id Terima kasih, Wassalamualaikum -Dirham',
  'repliedAt': datetime.datetime(2026, 5, 10, 14, 58, 34),
  'appVersion': '1.2.2'},
 {'reviewId': '4cca5261-5c30-4aa6-9bdb-fcbfc2d0d890',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'mantap pokoknya',
  'score': 5,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': None,
  'at': datetime.datetime(2026, 5, 10, 14, 53, 20),
  'replyContent': 'Assalamualaikum Bapak Vikar, terima kasih atas apresiasi yang diberikan kepada kami. Apabila ada saran atau informasi lainnya maka dapat disampaikan melalui layanan BSI Call 14040 atau melalui email resmi kami di contactus@bankbsi.co.id Terima kasih, Wassalamualaikum -Dirham',
  'repliedAt': datetime.datetime(2026, 5, 10, 14, 57, 35),
  'appVersion': None},
 {'reviewId': '099f125f-c691-4612-a5f7-951cc38c1706',
  'userName': 'Pengguna Google',
  'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g',
  'content': 'aplikasi ini mempermudah kita untuk menabung emas, untuk transaksi juga mudah',
  'score': 5,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '1.2.2',
  'at': datetime.datetime(2026, 5, 10, 14, 31, 58),

# Membuat Variable baru dengan nama "data_review1" dengan pandas-dataframe dan Menampilkannya

In [8]:
data_review1 = pd.DataFrame(review1)
display(data_review1)

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,86c5297f-cbbd-43c2-9653-a1061ad6f661,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,katanya bisa daftar lewat online tapi kenapa s...,1,0,1.2.2,2026-05-11 08:17:15,Assalamualaikum Ibu Cece. Mohon maaf atas keti...,2026-05-11 08:22:51,1.2.2
1,f4a34f38-9464-4b0e-bb53-c51821e3cf37,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Mantul Aplikasi Online BSI,5,0,None,2026-05-11 07:54:48,"Assalamualaikum Bapak Karsono, terima kasih at...",2026-05-11 08:05:29,None
2,cafee66b-df42-42f8-815e-05874c980a98,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,saya tdk suka apk bank ini sll update...ribet...,3,0,1.2.1,2026-05-11 07:37:28,"Assalamualaikum Bapak Duradji, mohon maaf dan ...",2026-05-11 07:46:26,1.2.1
3,46d9ddb6-4df1-431b-965b-0362e5015ea5,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Ini beneran gak bisa pelaporan transaksi? perc...,1,0,1.2.2,2026-05-11 07:30:12,"Assalamualaikum Bapak Abdussalam, Mohon maaf a...",2026-05-11 07:33:20,1.2.2
4,de9d502c-8ed5-49fa-9f8a-166ac34095f7,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Kenapa developer mode dianggap bermasalah, tid...",1,0,None,2026-05-11 07:29:46,"Assalamualaikum Bapak Angga, mohon maaf atas k...",2026-05-11 07:30:56,None
...,...,...,...,...,...,...,...,...,...,...,...
57808,d1cb5821-189a-4a2c-89ff-79d88b2b0b36,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasi nya keren banget, tampilan interface ...",5,2,None,2024-10-25 14:38:18,"\nAssalamualaikum Bapak/Ibu, terima kasih atas...",2024-11-10 06:40:30,None
57809,6a6c7fe3-4a99-43f2-9d1b-3d48d1003ad3,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,#Level Up to the Next Journey,5,0,1.0.1,2024-10-25 14:37:59,"Assalamualaikum Mr. Dede, thank you for your t...",2024-11-11 05:25:09,1.0.1
57810,fbd44595-f93c-47ea-97ce-8facce61d8a7,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Ok,5,0,1.0.1,2024-10-25 14:31:33,"Assalamualaikum Bapak Ilyas, terima kasih atas...",2024-11-11 05:25:53,1.0.1
57811,573558a9-b1a9-4e70-9b33-cf39c3f5a363,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,bagus,5,0,1.0.1,2024-10-25 14:22:32,"Assalamualaikum Bapak Eko, terima kasih atas k...",2024-11-11 05:26:39,1.0.1
57812,f12eab89-0709-4bba-bccc-bd8923ea6042,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aplikasi mobile banking paling lengkap,5,1,1.0.1,2024-10-25 14:18:41,"Assalamualaikum Bapak Sugiarto, terima kasih a...",2024-11-10 06:42:22,1.0.1

# Cek ada berapa panjang/baris datanya

In [9]:
data_reviews.shape

data_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              123 non-null    object
 1   userName              123 non-null    object
 2   userImage             123 non-null    object
 3   content               123 non-null    object
 4   score                 123 non-null    int64
 5   thumbsUpCount         123 non-null    int64
 6   reviewCreatedVersion  92 non-null     object
 7   at                    123 non-null    datetime64[ns]
 8   replyContent          0 non-null      object
 9   repliedAt             0 non-null      object
 10  appVersion            92 non-null     object
dtypes: datetime64[ns](1), int64(2), object(8)
memory usage: 10.7+ KB